"""add columns for inventory

Revision ID: 616e97cb8fb8
Revises: 452314c0d320
Create Date: 2023-09-26 11:24:13.570851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616e97cb8fb8'
down_revision = '452314c0d320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('count_inventory', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drug_facts', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_column('drug_facts')
        batch_op.drop_column('count_inventory')
        batch_op.drop_column('inventory')

    # ### end Alembic commands ###
